# ============================================================
# pg_hba.conf - Control de acceso del cliente
# SI3009 - Red de Monitoreo Ambiental
# ============================================================
# Formato: TYPE  DATABASE    USER        ADDRESS         METHOD

# Conexiones locales (dentro del contenedor)
local   all             all                             trust

# Conexiones IPv4 locales
host    all             all             127.0.0.1/32    trust

# Conexiones desde la red interna de Docker (172.16.0.0/12)
# Permite que réplicas y herramientas se conecten a la BD de app
host    all             all             172.16.0.0/12   md5
host    all             all             10.0.0.0/8      md5

# REPLICACIÓN: permite que las réplicas se conecten para streaming
# El usuario 'replicator' es de solo replicación (se crea en init)
host    replication     replicator      172.16.0.0/12   md5
host    replication     replicator      10.0.0.0/8      md5

# IPv6 local
host    all             all             ::1/128         trust
